### ISSUE TITLE
Validation result should be object

### ISSUE THREAD

**Issue by meeolin** [megazazik/validate#1]
Can we have object of errors instead Object-Array? Smth like this:
```
{
  all: {...},
  fields: {...},
}
```

**Comment by megazazik** [comment]
What are disadvantages of the current interface?
Is "hard to test" the only one?

**Comment by megazazik** [comment]
A validation result is an object now.
It has an `errors` field with errors set via fullObjectRules.
It looks like:
```js
{
  errors: [{type: 'someError'}],
  field1: {errors: [{type: 'field1Error'}]},
  field2: {errors: [{type: 'field2Error'}]}
}
```
